[2025-02-22T17:01:38.580+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-22T17:01:38.613+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: london_weather_pipeline.load_weather_data manual__2025-02-22T17:01:34.049883+00:00 [queued]>
[2025-02-22T17:01:38.624+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: london_weather_pipeline.load_weather_data manual__2025-02-22T17:01:34.049883+00:00 [queued]>
[2025-02-22T17:01:38.625+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-22T17:01:38.642+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): load_weather_data> on 2025-02-22 17:01:34.049883+00:00
[2025-02-22T17:01:38.648+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3355) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-22T17:01:38.650+0000] {standard_task_runner.py:72} INFO - Started process 3356 to run task
[2025-02-22T17:01:38.650+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'london_weather_pipeline', 'load_weather_data', 'manual__2025-02-22T17:01:34.049883+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/london_weather_pipeline/london_weather_etl.py', '--cfg-path', '/tmp/tmpasrjf_fe']
[2025-02-22T17:01:38.651+0000] {standard_task_runner.py:105} INFO - Job 41: Subtask load_weather_data
[2025-02-22T17:01:38.718+0000] {task_command.py:467} INFO - Running <TaskInstance: london_weather_pipeline.load_weather_data manual__2025-02-22T17:01:34.049883+00:00 [running]> on host ee2081ae3a04
[2025-02-22T17:01:38.865+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='london_weather_pipeline' AIRFLOW_CTX_TASK_ID='load_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-22T17:01:34.049883+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-22T17:01:34.049883+00:00'
[2025-02-22T17:01:38.866+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-22T17:01:38.884+0000] {base.py:84} INFO - Retrieving connection 'postgres_default'
[2025-02-22T17:01:38.899+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-22T17:01:38.916+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-22T17:01:38.917+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=london_weather_pipeline, task_id=load_weather_data, run_id=manual__2025-02-22T17:01:34.049883+00:00, execution_date=20250222T170134, start_date=20250222T170138, end_date=20250222T170138
[2025-02-22T17:01:38.984+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-22T17:01:39.026+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-22T17:01:39.029+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
