[2025-02-23T16:00:05.718+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-23T16:00:05.755+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: london_weather_pipeline.load_weather_data scheduled__2025-02-23T15:00:00+00:00 [queued]>
[2025-02-23T16:00:05.768+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: london_weather_pipeline.load_weather_data scheduled__2025-02-23T15:00:00+00:00 [queued]>
[2025-02-23T16:00:05.769+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-23T16:00:05.790+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): load_weather_data> on 2025-02-23 15:00:00+00:00
[2025-02-23T16:00:05.798+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=21077) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-23T16:00:05.800+0000] {standard_task_runner.py:72} INFO - Started process 21081 to run task
[2025-02-23T16:00:05.800+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'london_weather_pipeline', 'load_weather_data', 'scheduled__2025-02-23T15:00:00+00:00', '--job-id', '155', '--raw', '--subdir', 'DAGS_FOLDER/london_weather_pipeline/london_weather_etl.py', '--cfg-path', '/tmp/tmpa3tzsl9p']
[2025-02-23T16:00:05.802+0000] {standard_task_runner.py:105} INFO - Job 155: Subtask load_weather_data
[2025-02-23T16:00:05.889+0000] {task_command.py:467} INFO - Running <TaskInstance: london_weather_pipeline.load_weather_data scheduled__2025-02-23T15:00:00+00:00 [running]> on host ee2081ae3a04
[2025-02-23T16:00:06.074+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='london_weather_pipeline' AIRFLOW_CTX_TASK_ID='load_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-23T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-23T15:00:00+00:00'
[2025-02-23T16:00:06.076+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-23T16:00:06.100+0000] {base.py:84} INFO - Retrieving connection 'postgres_default'
[2025-02-23T16:00:06.115+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-23T16:00:06.145+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-23T16:00:06.146+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=london_weather_pipeline, task_id=load_weather_data, run_id=scheduled__2025-02-23T15:00:00+00:00, execution_date=20250223T150000, start_date=20250223T160005, end_date=20250223T160006
[2025-02-23T16:00:06.262+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-23T16:00:06.291+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-23T16:00:06.295+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
