[2025-02-23T16:00:05.867+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-23T16:00:05.909+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: newyork_weather_pipeline.load_weather_data scheduled__2025-02-23T15:00:00+00:00 [queued]>
[2025-02-23T16:00:05.926+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: newyork_weather_pipeline.load_weather_data scheduled__2025-02-23T15:00:00+00:00 [queued]>
[2025-02-23T16:00:05.927+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-23T16:00:05.947+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): load_weather_data> on 2025-02-23 15:00:00+00:00
[2025-02-23T16:00:05.956+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=21079) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-23T16:00:05.958+0000] {standard_task_runner.py:72} INFO - Started process 21087 to run task
[2025-02-23T16:00:05.959+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'newyork_weather_pipeline', 'load_weather_data', 'scheduled__2025-02-23T15:00:00+00:00', '--job-id', '158', '--raw', '--subdir', 'DAGS_FOLDER/newyork_weather_pipeline/newyork_weather_etl.py', '--cfg-path', '/tmp/tmpb2u9h9wc']
[2025-02-23T16:00:05.961+0000] {standard_task_runner.py:105} INFO - Job 158: Subtask load_weather_data
[2025-02-23T16:00:06.047+0000] {task_command.py:467} INFO - Running <TaskInstance: newyork_weather_pipeline.load_weather_data scheduled__2025-02-23T15:00:00+00:00 [running]> on host ee2081ae3a04
[2025-02-23T16:00:06.239+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='newyork_weather_pipeline' AIRFLOW_CTX_TASK_ID='load_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-23T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-23T15:00:00+00:00'
[2025-02-23T16:00:06.240+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-23T16:00:06.265+0000] {base.py:84} INFO - Retrieving connection 'postgres_default'
[2025-02-23T16:00:06.281+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-23T16:00:06.304+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-23T16:00:06.305+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=newyork_weather_pipeline, task_id=load_weather_data, run_id=scheduled__2025-02-23T15:00:00+00:00, execution_date=20250223T150000, start_date=20250223T160005, end_date=20250223T160006
[2025-02-23T16:00:06.374+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-23T16:00:06.391+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
