[2025-02-23T12:00:05.256+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-23T12:00:05.288+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: london_weather_pipeline.load_weather_data scheduled__2025-02-23T11:00:00+00:00 [queued]>
[2025-02-23T12:00:05.299+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: london_weather_pipeline.load_weather_data scheduled__2025-02-23T11:00:00+00:00 [queued]>
[2025-02-23T12:00:05.299+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-23T12:00:05.317+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): load_weather_data> on 2025-02-23 11:00:00+00:00
[2025-02-23T12:00:05.323+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=17888) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-23T12:00:05.324+0000] {standard_task_runner.py:72} INFO - Started process 17889 to run task
[2025-02-23T12:00:05.325+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'london_weather_pipeline', 'load_weather_data', 'scheduled__2025-02-23T11:00:00+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/london_weather_pipeline/london_weather_etl.py', '--cfg-path', '/tmp/tmp2cgv9w62']
[2025-02-23T12:00:05.326+0000] {standard_task_runner.py:105} INFO - Job 101: Subtask load_weather_data
[2025-02-23T12:00:05.404+0000] {task_command.py:467} INFO - Running <TaskInstance: london_weather_pipeline.load_weather_data scheduled__2025-02-23T11:00:00+00:00 [running]> on host ee2081ae3a04
[2025-02-23T12:00:05.546+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='london_weather_pipeline' AIRFLOW_CTX_TASK_ID='load_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-23T11:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-23T11:00:00+00:00'
[2025-02-23T12:00:05.547+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-23T12:00:05.565+0000] {base.py:84} INFO - Retrieving connection 'postgres_default'
[2025-02-23T12:00:05.579+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-23T12:00:05.597+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-23T12:00:05.597+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=london_weather_pipeline, task_id=load_weather_data, run_id=scheduled__2025-02-23T11:00:00+00:00, execution_date=20250223T110000, start_date=20250223T120005, end_date=20250223T120005
[2025-02-23T12:00:05.660+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-23T12:00:05.699+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-23T12:00:05.703+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
